dictCategories = {	# 'music' tags
					'sing': 'music', 
					'sings': 'music',
					'singer': 'music', 
					'album': 'music', 
					'albums': 'music',
					'rock': 'music',
					'pop': 'music',
					'dance': 'music',
					'music': 'music',

					# Movie tags
					'actor': 'movies', 
					'actress': 'movies',
					'directs': 'movies', 
					'director': 'movies', 
					'directors': 'movies', 
					'directed': 'movies', 
					'star': 'movies', 
					'stars': 'movies',
					'movie': 'movies', 
					'movies': 'movies',
					'oscar': 'movies',
					'oscars': 'movies',

					# Geography tags
					'where': 'geophraphy', 
					'capital': 'geophraphy', 
					'country': 'geophraphy', 
					'countries': 'geophraphy', 
					'continent': 'geophraphy',
					'continents': 'geophraphy', 
					'capital': 'geophraphy', 
					'capitals': 'geophraphy',
					'state': 'geophraphy',
					'border': 'geophraphy', 
					'borders': 'geophraphy',
					'river': 'geophraphy', 
					'sea': 'geophraphy',
					'mountain': 'geophraphy',
					'mountains': 'geophraphy',
				}